### ISSUE TITLE
Won't update unconditionally

### ISSUE THREAD

**Issue by AnKingMed** [Arthur-Milchior/SpecialFields#1]
It appears the add-on will not allow updating any cards now.  Every time I import (regardless of whether the deck being imported is older or newer) it says they are identical and doesn't import.  I tried true and false in the config

Edit: I can provide a video or pictures if you need

**Comment by AnKingMed** [comment]
Update.  I got the update to work, but only if I make the importing deck newer. It does not automatically import regardless.  The rest of the config seems to be working properly.   Attached are the decks I use in a new profile to test this.  Currently I can only import the "original" and then "new."  If I do "new" first, then it says the decks are identical and doesn't update anything
[test decks.zip](https://github.com/Arthur-Milchior/SpecialFields/files/4111639/test.decks.zip)

Edit: the update only works if     "update only if newer": false     If it is set to true, then it says the decks are identical even if the importing deck is newer so the add-on doesn't work at all

**Comment by AnKingMed** [comment]
@Arthur-Milchior I shot you a couple messages on reddit, but perhaps here is a better place to continue the conversation:  If you're able to fix this updating unconditionally issue and perhaps protecting the card styling, I think I can get you some support to make it worth your time. I don't want to bog you down too much, but just wanted to let you know I'm checking in with some contacts and it sounds like I'd be able to get a few dollars from multiple people since this would benefit so many.  Thanks for your help!

**Comment by Arthur-Milchior** [comment]
I see the error, sorry. please udate addon and try again

**Comment by AnKingMed** [comment]
Seems to be working well now! Thanks for the fix!   

Do you have any interest in trying to make it so it preserves card styling? If so, I'll chat with these other contacts and see if I can't get you a few bucks.   Also, we can give it a week or so and see if the special fields author responds. If not do you want to upload it on AnkiWeb or would you like me to? You could submit it as an official pull request and see what happens

**Comment by AnKingMed** [comment]
@Arthur-Milchior   Do you think it would be possible to have an option in the config for whether or not card styling is updated as mentioned above? And another for whether or not the deck description is updated? I’m finding those two are currently not updateable. If so, I’ve got a proposal for you. I’m unsure how much, but email me and I can send you details (ankingmed@gmail.com)

**Comment by Arthur-Milchior** [comment]
You can contact me at arthur@milchior.fr
I can clearly do it. I just need to take the time. And, to be perfectly honest, my job search is my biggest priority :s
